Data types for Go
codethesaurus/codethesaur.us pull request #261
Opened 2021-10-03 06:29 UTC by carlqt

## 📝 What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## 📖 Description
Fix for https://github.com/codethesaurus/codethesaur.us/issues/91

Adds Data Type docs for `Go`

## ✅ QA Instructions, Screenshots

![image](https://user-images.githubusercontent.com/5034394/135742771-7bb52bdd-e73c-4656-8b82-a8b626baab9c.png)

2021-10-03 23:04 UTC, geekygirlsarah commented
I'm curious: you have no code in here. Is there no actual keywords or anything to refer to these types?

2021-10-04 00:39 UTC, carlqt commented
Hi @geekygirlsarah , just curious what's the expectations here because I just pretty much followed the pattern that I see in the codebase. Is there something you have in mind so I could adjust my implementation?

2021-10-04 00:47 UTC, geekygirlsarah commented
If you look at C#'s for example: https://codethesaur.us/reference/?concept=data_types&lang=csharp and https://github.com/codethesaurus/codethesaur.us/blob/main/web/thesauruses/csharp/data_types.json

It lists the keywords that are those data types in the `code` keys. While you have the `code` blocks,they all looked empty. You did do the `not-implemented` parts right.

So I'm wondering: are there data type keywords in Go? (I don't know it well enough to know and I'm on a plane and not in a good spot to verify right now.)

2021-10-04 00:55 UTC, carlqt commented
Ahhh now I got it. Yes, there are. Let me update my implementations then. Thanks for the review

2021-10-04 01:10 UTC, carlqt commented
Updated the PR

2021-10-06 00:20 UTC, geekygirlsarah requested changes

2021-10-06 00:20 UTC, geekygirlsarah commented on web/thesauruses/go/data_types.json
> +      "code": ""
Is this also a `not-implemented`?

2021-10-06 00:20 UTC, geekygirlsarah commented on web/thesauruses/go/data_types.json
> +      "code": ""
Same for these below, are they not-implemented?

2021-10-06 00:20 UTC, geekygirlsarah commented on web/thesauruses/go/data_types.json
> +      "code": ""
For the `not-implemented` ones, you can remove the `code` lines too.

2021-10-06 00:40 UTC, carlqt commented
Thanks for the review. Question, what if there are types here that I'm unsure like `complex_as_object`? What should I do for that?

2021-10-06 15:25 UTC, geekygirlsarah commented
> 
> 
> Thanks for the review. Question, what if there are types here that I'm unsure like `complex_as_object`? What should I do for that?

Good question! I tried to make descriptions in the _meta files for what they are. If they're not clear, you can always ask here or email/tweet too. (For example, that's a native object that can store a complex number (like `3 + 4i`).)

You could also leave them essentially undefined (like delete the concept ID `complex_as_object` all over) and that'll show that its state is unknown. I don't prefer this, but the site is set up to accept this as a potential thing as the meta files can evolve when these files may not always be in sync with them.

2021-10-06 22:30 UTC, carlqt commented
> You could also leave them essentially undefined (like delete the concept ID complex_as_object all over) and that'll show that its state is unknown. I don't prefer this, but the site is set up to accept this as a potential thing as the meta files can evolve when these files may not always be in sync with them.

You mentioend that you don't prefer leaving it `blank` if the type is unknown, so what's the preference? I've updated the PR with the new changes maybe you can check if that's satisfactory or needs more tweak.

2021-10-06 23:48 UTC, geekygirlsarah commented
You can use `"not-implemented": true` on it instead of code. (You can optionally still have a comment)

2021-10-10 13:37 UTC, carlqt commented
Hi, I've updated the PR

2021-10-13 01:59 UTC, geekygirlsarah commented
You force pushed? It makes it hard to see what changed since I asked for revisions! But reviewing it all again, it looks right so I'll merge it.

Don't forget to sign up for Hacktoberfest if you haven't so this can count towards the shirt/stickers!

2021-10-13 02:00 UTC, merged

2021-10-13 12:26 UTC, carlqt commented
@geekygirlsarah Thanks. Sorry, I forced push out of habit 😭 .

2021-10-15 05:02 UTC, geekygirlsarah commented
It's alright, it's a fairly small file and easy to re-review.