Added operators.json file for javascript. Resolves #303
codethesaurus/codethesaur.us pull request #313
Opened 2021-10-05 07:13 UTC by untamedImpala

Resolves #303

Added operators,json in javascript and updated it according to EC6 Standard of JS.

## Reviewer Steps

- [ ] Review commits
- [ ] (If needed) Approve first run of workflow
- [ ] (If needed) Activate Heroku Review app
- [ ] Verify any changes in Deploy Preview
- [ ] Approve and/or merge changes

2021-10-05 14:00 UTC, geekygirlsarah commented
This is close, but needs a few tweaks. If you could do those, then I'd merge it in!

2021-10-05 16:23 UTC, untamedImpala commented
@geekygirlsarah yeah sure, tell me.

2021-10-05 19:48 UTC, geekygirlsarah requested changes

2021-10-05 19:48 UTC, geekygirlsarah commented on web/thesauruses/javascript/operators.json
> +		"language_version": "ES2015",
For this, I'd rather have one of the newest versions (ES2020 or ES2021). I am reasonably confident that the operators for this probably haven't changed, so that makes this pretty easy. But would you be willing to update this?

2021-10-05 19:48 UTC, geekygirlsarah commented on web/thesauruses/javascript/operators.json
> +		"is": {
This sounds like it should be `not-implemented: true`, right?

2021-10-05 19:48 UTC, geekygirlsarah commented on web/thesauruses/javascript/operators.json
> +		"is_not": {
Same for this, `not-implemented: true`

2021-10-05 19:48 UTC, geekygirlsarah commented on web/thesauruses/javascript/operators.json
> +			"not-implemented": "true",
If they're not implemented, you can take out the `code` key. (It cleans it up a bit and leads to less confusion.)

There's several places this exists, so you could maybe do a replace all in your editor to get rid of all of them.

2021-10-05 19:48 UTC, geekygirlsarah commented on web/thesauruses/javascript/operators.json
> +		"and_assignment": {
I noticed you had some things like XOR assignment filled in but the AND assignment isn't. It does exist in JS (see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Bitwise_AND_assignment ). It's just `&=`.

2021-10-05 19:48 UTC, geekygirlsarah commented on web/thesauruses/javascript/operators.json
> +			"code": ":?"
This should be `condition ? true_expression : false_expression` (you swapped `:` and `?`).

2021-10-05 19:48 UTC, geekygirlsarah commented
I added review comments but GitHub didn't send those out before I said it needed tweaks. Sorry about that...

2021-10-06 08:06 UTC, fla-t commented on web/thesauruses/javascript/operators.json
> +		"is_not": {
yeah forgot about that.

2021-10-06 08:06 UTC, untamedImpala commented on web/thesauruses/javascript/operators.json
> +			"not-implemented": "true",
okay.

2021-10-06 08:11 UTC, fla-t commented on web/thesauruses/javascript/operators.json
> +		"and_assignment": {
yeah I actually mixed XOR assignment with AND, and left AND as blank.

2021-10-06 08:11 UTC, fla-t commented on web/thesauruses/javascript/operators.json
> +			"code": ":?"
omg, stupid me. fixing all of these rn.

2021-10-06 08:19 UTC, untamedImpala commented
Sorry, I accidentally deleted the last commit on my local git, and now I just have a new commit that contains all of my changes. I hope this doesn't cause any problems for you.

2021-10-06 15:27 UTC, geekygirlsarah commented on web/thesauruses/javascript/operators.json
> +			"comment": "There is also === which means strict equality"
This is a good point. I should add that into meta's operators.json too. I'll make an issue for that.

2021-10-06 19:01 UTC, untamedImpala commented on web/thesauruses/javascript/operators.json
> +			"comment": "There is also === which means strict equality"
should I add it? if not tell me if there is something missing in this pr?

2021-10-07 01:50 UTC, geekygirlsarah commented on web/thesauruses/javascript/operators.json
> +			"comment": "There is also === which means strict equality"
No, I prefer things added to the meta language files to be done in a separate PR. (Which you can do if you want or maybe I'll try to tackle this tonight.)

2021-10-07 01:52 UTC, geekygirlsarah commented
I think this now looks good. I'll merge it in! Thank you for helping out!

If you haven't signed up for [Hacktoberfest](https://hacktoberfest.digitalocean.com) yet, you should so this PR can count towards the free swag!

2021-10-07 01:52 UTC, merged

2021-10-07 04:56 UTC, fla-t commented
Yes, I have done that, in fact this is my first time participating in open source repos. By far it's going quite well. I have also contributed to a small retro game engine. Fun experience 10/10.

Edit: tbh, I would love the shirt. Would be a huge flex in the university. :)

2021-10-08 03:06 UTC, geekygirlsarah commented
I have a few of the shirts from past years. I do feel sort of awesome wearing them around! Good luck on the rest of your PRs!