Add operators.json for C++. Resolves #298
codethesaurus/codethesaur.us pull request #315
Opened 2021-10-05 08:20 UTC by Ranjana-Kambhammettu

## What GitHub issue does this PR apply to?

Resolves #298 

## What changed and why?

Added operators.json file and added the code for all the relevant operators in C++.

## (If editing Django app) Please add screenshots

## Any additional comments or things to be aware of while reviewing?

## Reviewer Steps

- [ ] Review commits
- [ ] (If needed) Approve first run of workflow
- [ ] (If needed) Activate Heroku Review app
- [ ] Verify any changes in Deploy Preview
- [ ] Approve and/or merge changes

2021-10-07 01:57 UTC, geekygirlsarah requested changes

2021-10-07 01:57 UTC, geekygirlsarah commented on web/thesauruses/cpp/operators.json
> +      "code": ""
For the `not-implemented` ones, could you remove the `code` lines?

2021-10-07 01:57 UTC, geekygirlsarah commented
I think this is good if you remove the code blocks from the not-implemented parts. Then I'll merge it in!

2021-10-07 04:20 UTC, Ranjana-Kambhammettu commented on web/thesauruses/cpp/operators.json
> +      "code": ""
I have made the necessary changes 👍🏽

2021-10-08 03:04 UTC, geekygirlsarah commented
The JSON Check failed because the JSON file isn't valid. Looks like every line with `not-implemented: true` has trailing commas at the end of each line, which isn't valid. If you remove those and the check passes, I can merge it in.

2021-10-08 03:05 UTC, geekygirlsarah requested changes

2021-10-08 03:05 UTC, geekygirlsarah commented on web/thesauruses/cpp/operators.json
> +      "not-implemented": "true",
Lines that seem to have `not-implemented` have trailing commas, which aren't valid JSON.

2021-10-08 03:41 UTC, Ranjana-Kambhammettu commented on web/thesauruses/cpp/operators.json
> +      "not-implemented": "true",
I have made the necessary changes.

2021-10-08 04:57 UTC, geekygirlsarah commented
Alright, this passed the checks! I'll merge it in. Thank you!

Don't forget this counts for the Hacktoberfest shirt if you're signed up.

2021-10-08 04:57 UTC, merged