Edits to Python Control Structure
codethesaurus/codethesaur.us pull request #316
Opened 2021-10-05 08:41 UTC by darensin01

## What changed and why?

- Added list comprehension entry for Python (also had to edit `_meta`)
- Added code sample to iterate through an iterable of tuples
- Added concept of `break` under `while` loop

## Reviewer Steps

- [ ] Review commits
- [ ] (If needed) Approve first run of workflow
- [ ] (If needed) Activate Heroku Review app
- [ ] Verify any changes in Deploy Preview
- [ ] Approve and/or merge changes

2021-10-05 14:10 UTC, geekygirlsarah commented
Hey @darensin01, I appreciate you pointing out the missing things, both in Python and across the "meta" language!

I generally prefer making these kinds of contributions in separate PRs since the meta language stuff affects all the languages and can sometimes break things if not done right. However, it's a small addition and I think it'll probably work here.

I may want to split out the `break`, so let me think on that today.

2021-10-05 14:15 UTC, geekygirlsarah commented
I think if you make the few suggested changes, I'll go ahead and merge it in!

2021-10-05 14:27 UTC, darensin01 commented
Hi @geekygirlsarah, thanks! Just to clarify, what changes do you suggest I make?

2021-10-05 14:39 UTC, geekygirlsarah commented
> 
> 
> Hi @geekygirlsarah, thanks! Just to clarify, what changes do you suggest I make?

I made multiple review comments. See https://github.com/codethesaurus/codethesaur.us/pull/316/files for them.

2021-10-05 14:52 UTC, geekygirlsarah requested changes

2021-10-05 14:52 UTC, geekygirlsarah commented on web/thesauruses/_meta/control_structures.json
> +    "list_comprehension": {
You technically did this correct, however, can you add `list_comprehension` in the same order as they are above? (so after the `foreach_loop`)

2021-10-05 14:52 UTC, geekygirlsarah commented on web/thesauruses/python/control_structures.json
> +      "code": "while condition:\n    statements\n\nwhile True:\n    statements\n    if(conditional):\n        break"
Can you add a `"comment"` here describing the two different scenarios you have since it's not technically one code block?

2021-10-05 14:52 UTC, geekygirlsarah commented on web/thesauruses/python/control_structures.json
> +      "code": "for iterator in iterable:\n    statements\n\nfor first, second in iterable_of_tuples:\n    foo(first)\n    bar(second)"
Same here, add a `"comment"` for the two blocks.

2021-10-05 14:52 UTC, geekygirlsarah commented on web/thesauruses/python/control_structures.json
> +      "code": "[foo(item) for item in iterable]\n[foo(item) for item in iterable if conditional(item)]"
Why do you have `[` and `]` around these? You don't use those in Python's list comprehensions. The code should be technically compilable.

2021-10-05 14:52 UTC, geekygirlsarah commented
Sorry, I missed a step on sending the review. (I thought you saw it, apparently you didn't!)

2021-10-05 15:11 UTC, darensin01 commented
Yup, I just saw them! Thought I was seeing things (or a lack thereof in this case)! I will work on them, thanks :)

2021-10-07 02:19 UTC, iedr commented on web/thesauruses/python/control_structures.json
> +      "code": "[foo(item) for item in iterable]\n[foo(item) for item in iterable if conditional(item)]"
Hi @geekygirlsarah, Python's list comprehensions are supposed to have square brackets around them...
For example, see [https://www.w3schools.com/python/python_lists_comprehension.asp](https://www.w3schools.com/python/python_lists_comprehension.asp). 

I've put in `new_list = [...]` to make it clearer. Also put in a comment since there are 2 blocks of list comprehensions here.

2021-10-08 01:16 UTC, geekygirlsarah commented
I appreciate the updates! I'll merge it in!

Don't forget to sign up for Hacktoberfest if you haven't already!

2021-10-08 01:16 UTC, merged

2021-10-08 01:21 UTC, geekygirlsarah commented
There's a failed pipeline/workflow/github action on this. That's my fault and not reflective of this. (I've since deleted the action that's causing the error)