Added operators.json for Swift
codethesaurus/codethesaur.us pull request #318
Opened 2021-10-05 12:28 UTC by Rutujabadve

## What GitHub issue does this PR apply to?

Resolves #311

## Added operators.json to Swift

## (If editing Django app) Please add screenshots

## Any additional comments or things to be aware of while reviewing?

## Reviewer Steps

- [ ] Review commits
- [ ] (If needed) Approve first run of workflow
- [ ] (If needed) Activate Heroku Review app
- [ ] Verify any changes in Deploy Preview
- [ ] Approve and/or merge changes

2021-10-07 02:03 UTC, geekygirlsarah requested changes

2021-10-07 02:03 UTC, geekygirlsarah commented on web/thesauruses/swift/operators.json
> +      "code": ""
For the lines that are marked `not-implemented`, could you remove the code blocks? It'll help keep the files cleaner and maybe lead to less confusion.

2021-10-07 02:03 UTC, geekygirlsarah commented
If you make that little change, I think this can be merged in!

2021-10-07 06:26 UTC, Rutujabadve commented
I have opened another PR for the requested changes

2021-10-08 03:33 UTC, geekygirlsarah commented
Wait, did you make two PRs for the same issue? I'm not sure how I didn't notice this, but also curious how it happened.

2021-10-08 03:36 UTC, geekygirlsarah commented
Wait, did you make two PRs for the same issue? I'm not sure how I didn't notice this.

Since this is a duplicate, and the merge conflict is for changes that undo changes in the other one, I'm going to close this PR. (You got Hacktoberfest credit for the other one at least.)

2021-10-08 03:36 UTC, closed without merging

2021-10-08 04:14 UTC, Rutujabadve commented
Actually I an new to open source I dint know you could reopen a PR. I was going to close this one.Sorry for inconvinence.

2021-10-08 04:58 UTC, geekygirlsarah commented
Oh that's alright! I'm here for helping newer experience people and newer open source contributors learn!