Nim add operators
codethesaurus/codethesaur.us pull request #320
Opened 2021-10-05 14:28 UTC by juancarlospaco

## What GitHub issue does this PR apply to?

Resolves https://github.com/codethesaurus/codethesaur.us/issues/304

## What changed and why?

- Add Nim operators.

## (If editing Django app) Please add screenshots

No

## Any additional comments or things to be aware of while reviewing?
 
No

## Reviewer Steps

- [ ] Review commits
- [ ] (If needed) Approve first run of workflow
- [ ] (If needed) Activate Heroku Review app
- [ ] Verify any changes in Deploy Preview
- [ ] Approve and/or merge changes

2021-10-05 14:43 UTC, geekygirlsarah commented
If you make the couple of minor changes, I'll merge it in!

2021-10-05 14:44 UTC, juancarlospaco commented
What change ?.

2021-10-05 14:45 UTC, geekygirlsarah commented
Hmm... I made review comments. (See above.)  Maybe Github doesn't email those?

2021-10-05 14:49 UTC, juancarlospaco commented
![2021-10-05_07-48](https://user-images.githubusercontent.com/1189414/136046798-05cdcf14-1fcf-4510-9e70-d0ac617345ee.png)

No review comments for me.

2021-10-05 14:51 UTC, geekygirlsarah requested changes

2021-10-05 14:51 UTC, geekygirlsarah commented on web/thesauruses/nim/operators.json
> +      "not-implemented": "true"
If a concept is `not-implemented`, you can remove the `code` line. (same for the other lines below.)

2021-10-05 14:51 UTC, geekygirlsarah commented on web/thesauruses/nim/operators.json
> +      "code": ""
Does this exist or is it `not-implemented` too? I'm guessing maybe it's not implemented but you forgot the line?

2021-10-05 14:51 UTC, juancarlospaco commented
I see it now! 🙂

2021-10-05 14:51 UTC, geekygirlsarah commented
Oooooh, apparently I missed a step. I thought "pending" meant "they hadn't worked on it yet" not "you haven't sent it to them yet"...

![image](https://user-images.githubusercontent.com/2601974/136047308-01a9deaa-c28c-4f2f-96fe-befd562de3bb.png)

2021-10-05 15:02 UTC, juancarlospaco commented
Good to know, so is not visible for other people until you confirm the review, interestin'

2021-10-07 02:07 UTC, geekygirlsarah requested changes

2021-10-07 02:07 UTC, geekygirlsarah commented on web/thesauruses/nim/operators.json
> +      "name": "Addition operator",
Sorry, I didn't end up catching this last time. Can you remove all the `name` lines? those are pulled in from the meta language and aren't needed in this file.

(Then I'll merge it. I swear!)

2021-10-07 02:16 UTC, juancarlospaco commented on web/thesauruses/nim/operators.json
> +      "name": "Addition operator",
No drama. 🙂

2021-10-08 02:50 UTC, geekygirlsarah requested changes

2021-10-08 02:50 UTC, geekygirlsarah commented on web/thesauruses/nim/operators.json
> +      "code": ""
Looks like you still have an empty code line here. Is it missing the code, or does it need to be `not-implemented`?

2021-10-08 09:13 UTC, juancarlospaco commented on web/thesauruses/nim/operators.json
> +      "code": ""
Fixed.

2021-10-10 05:10 UTC, geekygirlsarah commented on web/thesauruses/nim/operators.json
> +      "code": ""
I'm still seeing the empty code block. I just looked it up and Nim doesn't have an `xnor`, so this should have `code` removed and `"not-implemented": true` in its place.

2021-10-10 13:09 UTC, juancarlospaco commented on web/thesauruses/nim/operators.json
> +      "code": ""
Sorry, you are right, should be Ok now.
The JSON changed since last time I edited it, but is a good change.

2021-10-10 14:54 UTC, geekygirlsarah commented
Thanks for fixing that last part! I'll merge this in! 

And sign up for Hacktoberfest if you haven't! This counts towards the swag!

2021-10-10 14:54 UTC, merged