Added Python operators
codethesaurus/codethesaur.us pull request #323
Opened 2021-10-05 16:02 UTC by RiyaM16

## What GitHub issue does this PR apply to?

Resolves #307 

## What changed and why?

Added Python operators.

## (If editing Django app) Please add screenshots

NA

## Checklist

- [X] I claimed any associated issue(s) and they are not someone else's
- [X] I have looked at documentation to ensure I made any revisions correctly
- [X] I tested my changes locally to ensure they work
- [ ] (If editing Django) I have added or edited any appropriate unit tests for my changes

## Any additional comments or things to be aware of while reviewing?

NA

2021-10-07 02:09 UTC, geekygirlsarah requested changes
I think if you make this small change, I can merge it in!

2021-10-07 02:09 UTC, geekygirlsarah commented on web/thesauruses/python/operators.json
> +      "code": ""
If there's concepts that are marked `not-implemented`, can you remove the `code` blocks? It'll make the files a little cleaner as they're not needed here.

2021-10-07 04:34 UTC, RiyaM16 commented
Hi @geekygirlsarah!
I've made the needed changes.

2021-10-08 02:53 UTC, geekygirlsarah commented
Yeah, I think this looks good to me! I'll merge it.

Thanks for working on this! Don't forget to sign up for Hacktoberfest if you haven't already, this will count towards it!

2021-10-08 02:53 UTC, merged