Closes #302
codethesaurus/codethesaur.us pull request #324
Opened 2021-10-05 17:28 UTC by vinayak0127

## What GitHub issue does this PR apply to?

Resolves #302 

## What changed and why?

## (If editing Django app) Please add screenshots

## Checklist

- [x] I claimed any associated issue(s) and they are not someone else's
- [x] I have looked at the documentation to ensure I made any revisions correctly
- [x] I tested my changes locally to ensure they work
- [x] (If editing Django) I have added or edited any appropriate unit tests for my changes

## Any additional comments or things to be aware of while reviewing?

2021-10-07 02:12 UTC, geekygirlsarah requested changes
I think if you make these tweaks, I'll merge it in!

2021-10-07 02:12 UTC, geekygirlsarah commented on web/thesauruses/java/operators.json
> +    "language": "language_id",
Can you fill out these 3 lines to reflect that it's Java, and the latest version of Java?

2021-10-07 02:12 UTC, geekygirlsarah commented on web/thesauruses/java/operators.json
> +      "code": "",
For the `not-implemented` concepts, can you remove the `code` lines? It'll help clean up the file as they're not needed here.

2021-10-07 10:12 UTC, vinayak0127 commented
Hey! @geekygirlsarah I have updated the changes can you review them.

2021-10-08 04:36 UTC, geekygirlsarah approved these changes

2021-10-08 04:41 UTC, geekygirlsarah commented
With the new changes, I think this works. I'll merge it in!

Don't forget to sign up for Hacktoberfest if you want. This counts towards the shirt/swag!

2021-10-08 04:41 UTC, merged