Fixes #270
codethesaurus/codethesaur.us pull request #325
Opened 2021-10-05 20:13 UTC by somya-15

## What GitHub issue does this PR apply to?

Resolves #270 

## What changed and why?

Added a JSON file named "classes.json" under codethesaur.us/web/thesauruses. The file contains the required java classes syntax/code as per the description in the document.

## Checklist

- [X] I claimed any associated issue(s) and they are not someone else's
- [X] I have looked at documentation to ensure I made any revisions correctly
- [X] I tested my changes locally to ensure they work
- [ ] (If editing Django) I have added or edited any appropriate unit tests for my changes

## Any additional comments or things to be aware of while reviewing?

After reviewing similar JSON files for java data_types and conditional statements I have tried to follow the best coding practices observable in these files.

2021-10-07 02:21 UTC, geekygirlsarah requested changes
I will probably need to review again after these changes, but this looks pretty good so far and very well thought out! If you make those changes, I can probably merge it in!

2021-10-07 02:21 UTC, geekygirlsarah commented on web/thesauruses/java/classes.json
> +			"code": "access-modifier class ClassName {\n  Class body containing variables and methods \n}"
One of the things I strive to have on Code Thesaurus is for the code blocks to be technically compileable. Technically "Class body containing variables and methods" would throw syntax errors, so it's not valid Java. Can you turn things like those into comments so someone could actually copy/paste this into their code and it would work? (Same for the concepts below too)

2021-10-07 02:21 UTC, geekygirlsarah commented on web/thesauruses/java/classes.json
> +			"code": "",
For concepts that are marked `not-implemented`, can you remove the `code` blocks? It'll just help clean up the files a little bit.

2021-10-07 08:49 UTC, somya-15 commented
Hello, I have made the necessary changes as requested. Kindly review the updates and let me know if we can further improvise the document.

2021-10-08 03:57 UTC, geekygirlsarah approved these changes

2021-10-08 03:58 UTC, geekygirlsarah commented
I think it looks good now! Thank you!

Don't forget to sign up for Hacktoberfest if you haven't already. This will count towards the shirt/swag!

2021-10-08 03:58 UTC, merged