Added Swift Data Types
codethesaurus/codethesaur.us pull request #326
Opened 2021-10-06 00:05 UTC by gildedgardenia

## What GitHub issue does this PR apply to?

Resolves #89

## What changed and why?

Added information about data types in Swift.

## Please add screenshots

<img width="1366" alt="swift-data-types-page" src="https://user-images.githubusercontent.com/17087389/136120064-14245d88-ac0c-4151-b39e-a08ee9c5eb04.png">

## Checklist

- [x] I claimed any associated issue(s) and they are not someone else's
- [x] I have looked at documentation to ensure I made any revisions correctly
- [x] I tested my changes locally to ensure they work
- [ ] (If editing Django) I have added or edited any appropriate unit tests for my changes

## Any additional comments or things to be aware of while reviewing?

Swift types were somewhat hard to classify! Please let me know if something doesn't make sense!

2021-10-07 02:24 UTC, geekygirlsarah requested changes
I think this is pretty good. Make the couple of small changes and I can merge it in!

2021-10-07 02:24 UTC, geekygirlsarah commented on web/thesauruses/swift/data_types.json
> +     "language": "language_id",
Can you update the language to be `swift` and the version to be whatever the latest version to me?

2021-10-07 02:24 UTC, geekygirlsarah commented on web/thesauruses/swift/data_types.json
> +       "comment": "``Int`` is used in situations where the platform size may not be known. On a 32-bit platform, ``Int`` can store 32-bit integers."
I'm curious about the double backticks. There's now Markdown support, so you probably only need one of them on each side for it to render right on the site.

2021-10-11 23:36 UTC, gildedgardenia commented on web/thesauruses/swift/data_types.json
> +     "language": "language_id",
Done!

2021-10-11 23:36 UTC, gildedgardenia commented on web/thesauruses/swift/data_types.json
> +       "comment": "``Int`` is used in situations where the platform size may not be known. On a 32-bit platform, ``Int`` can store 32-bit integers."
The double backticks is a bad habit that I keep carrying over from writing RST. I switched them to single backticks. Thanks!

2021-10-13 02:39 UTC, geekygirlsarah commented on web/thesauruses/swift/data_types.json
> +       "comment": "``Int`` is used in situations where the platform size may not be known. On a 32-bit platform, ``Int`` can store 32-bit integers."
Oooh, RST. That makes sense. Also I've learned double-backticks do something special in Markdown, so I guess they're not _wrong_ but do something different than I think you were expecting.

2021-10-13 02:41 UTC, geekygirlsarah commented
I think this should work! I'll merge it in.

Thanks again! Don't forget to sign up for Hacktoberfest if you haven't yet! You're halfway there!

2021-10-13 02:41 UTC, merged