Scala operators.json details added.
codethesaurus/codethesaur.us pull request #331
Opened 2021-10-06 05:12 UTC by chaitanyks

## What GitHub issue does this PR apply to?

Resolves #310 

## What changed and why?

## (If editing Django app) Please add screenshots

## Checklist

- [x] I claimed any associated issue(s) and they are not someone else's
- [ ] I have looked at documentation to ensure I made any revisions correctly
- [x] I tested my changes locally to ensure they work
- [ ] (If editing Django) I have added or edited any appropriate unit tests for my changes

## Any additional comments or things to be aware of while reviewing?

2021-10-06 15:37 UTC, chaitanyks commented
![Scala_image](https://user-images.githubusercontent.com/25911060/136236085-38de1e4e-adb0-4204-a057-3f4f0af9de06.png)

Changes are working fine.

2021-10-07 02:43 UTC, geekygirlsarah requested changes
I think with a few changes, I'd be happy to merge this in. I'll make an issue for the new operators to edit the meta one. You're welcome to take that if you want or I'll add it in possibly tonight or tomorrow.

2021-10-07 02:43 UTC, geekygirlsarah commented on web/thesauruses/scala/operators.json
> +      "name": "Addition operator",
I saw you didn't look over the documentation, but in the language files, you should take out the `name` lines as those are pulled in from the meta files and aren't needed here.

2021-10-07 02:43 UTC, geekygirlsarah commented on web/thesauruses/scala/operators.json
> +      "code": ""
For the `not-implemented` concepts, can you remove the `code` lines? It just cleans up the file when no code is needed.

2021-10-07 02:43 UTC, geekygirlsarah commented on web/thesauruses/_meta/operators.json
> +      "binary_and",
This issue is _just_ for editing Scala's language operators. The meta ones shouldn't be edited in the same PR. But also the binary AND and OR and etc. are the bitwise ones above (`and` and `or`) so these are duplicates. The one's compliment and zero fill might be good additions but should be reported in a separate issue.

Can you remove these lines you added to take this file back to its original state, and then remove the added concepts in the Scala operators file too?

2021-10-07 06:35 UTC, chaitanyks commented on web/thesauruses/_meta/operators.json
> +      "binary_and",
Yaa sure.

2021-10-07 06:39 UTC, chaitanyks commented on web/thesauruses/scala/operators.json
> +      "name": "Addition operator",
Fixed.

2021-10-07 06:39 UTC, chaitanyks commented on web/thesauruses/scala/operators.json
> +      "code": ""
Fixed.

2021-10-08 03:40 UTC, geekygirlsarah commented
With the changes, I think this looks good! I'll merge it in.

It counts towards Hacktoberfest, so be sure to sign up for that if you haven't to get a shirt/swag!

2021-10-08 03:40 UTC, merged