Added Golang Logic/Math Operators
codethesaurus/codethesaur.us pull request #334
Opened 2021-10-06 15:55 UTC by 26tanishabanik

## What GitHub issue does this PR apply to?

Resolves #300 

## What changed and why?

## (If editing Django app) Please add screenshots

## Checklist

- [x] I claimed any associated issue(s) and they are not someone else's
- [x] I have looked at documentation to ensure I made any revisions correctly
- [x] I tested my changes locally to ensure they work
- [ ] (If editing Django) I have added or edited any appropriate unit tests for my changes

## Any additional comments or things to be aware of while reviewing?

2021-10-07 02:55 UTC, geekygirlsarah requested changes
I think with the tweaks mentioned in here, I'd be happy to merge it in!

2021-10-07 02:55 UTC, geekygirlsarah commented on web/thesauruses/go/operators.json
> +      "name": "Addition operator",
You can remove all the `name` lines as the site doesn't pull text from the language files.

2021-10-07 02:55 UTC, geekygirlsarah commented on web/thesauruses/go/operators.json
> +      "code": ""
You can remove `code` lines from any of the `not-implemented: true` concepts. It just makes it a bit cleaner.

2021-10-07 02:55 UTC, geekygirlsarah commented on web/thesauruses/go/operators.json
> +    },
I'm pretty sure this isn't in the meta `operators.json` file. You can't really add in new things like this. If you think things are missing, you're welcome to add an issue to have someone add them, but they don't really work on a single language like this.

Can you remove these or any other ones you added in?

2021-10-07 04:30 UTC, 26tanishabanik commented on web/thesauruses/go/operators.json
> +    },
Sure, I will strictly follow the operators.json, also do you want me to remove the "name" tag from all the objects?

2021-10-20 05:23 UTC, geekygirlsarah commented
Hey @26tanishabanik! It's been about two weeks since you made this PR and I suggested some changes. Is it still going ok? Do you have any questions?

2021-10-20 05:47 UTC, 26tanishabanik commented
> Hey @26tanishabanik! It's been about two weeks since you made this PR and I suggested some changes. Is it still going ok? Do you have any questions?

I have asked you a question above, can you please answer that first?

2021-10-23 03:42 UTC, geekygirlsarah commented
> I have asked you a question above, can you please answer that first?

I missed that. It would have been faster for you to re-ask it or quote it or something.

2021-10-23 03:42 UTC, geekygirlsarah commented on web/thesauruses/go/operators.json
> +    },
Yes, remove `name` since that's in the meta language file.

2021-10-30 17:28 UTC, geekygirlsarah commented
Hi @26tanishabanik! It's been about a week since my response to your question. How is this coming along? Do you have any questions?

2021-10-30 17:32 UTC, 26tanishabanik commented
> Hi @26tanishabanik! It's been about a week since my response to your question. How is this coming along? Do you have any questions?

I am really sorry, I have been busy with my academic assignments, I will surely update it by tomorrow. My sincere apologies for the delay.

2021-10-30 18:58 UTC, geekygirlsarah commented
> 
> I am really sorry, I have been busy with my academic assignments, I will surely update it by tomorrow. My sincere apologies for the delay.

That's alright. I just wanted to make sure you weren't stuck and if you wanted to get it done in time for Hacktoberfest it wasn't me holding you up.

2021-11-25 02:49 UTC, geekygirlsarah commented
Hey @26tanishabanik, how is this coming along? Do you have any questions or anything you need from me to finish this PR?

2021-11-25 11:07 UTC, 26tanishabanik commented
> Hey @26tanishabanik, how is this coming along? Do you have any questions or anything you need from me to finish this PR?

Hey @geekygirlsarah sorry for the delay, its done, PR no #452

2021-11-28 15:57 UTC, geekygirlsarah commented
Oh... I was expecting you to make the changes to this PR. You can always keep adding more commits to the same branch and they'll always get automatically added into the same PR.

Just to confirm... should this PR be closed in favor of #452 instead?

2021-11-28 15:58 UTC, closed without merging

2021-11-28 16:10 UTC, 26tanishabanik commented
> Oh... I was expecting you to make the changes to this PR. You can always keep adding more commits to the same branch and they'll always get automatically added into the same PR.
> 
> ~Just to confirm... should this PR be closed in favor of #452 instead?~ Never mind, I already merged the other one. I'll close this then.

Sure