Added C# Logic/Math Operators
codethesaurus/codethesaur.us pull request #335
Opened 2021-10-06 16:30 UTC by VaishnaviNandakumar

## What GitHub issue does this PR apply to?

Resolves #299 

## What changed and why?

## (If editing Django app) Please add screenshots

## Checklist

- [x] I claimed any associated issue(s) and they are not someone else's
- [x] I have looked at documentation to ensure I made any revisions correctly
- [x] I tested my changes locally to ensure they work
- [ ] (If editing Django) I have added or edited any appropriate unit tests for my changes

## Any additional comments or things to be aware of while reviewing?
Additional operators (conditional_and, conditional_and_assignment, conditional_or, conditional_or_assignment) have been included.

2021-10-06 19:23 UTC, VaishnaviNandakumar commented
Hi @geekygirlsarah! The initial commit also included the Source folder which had to be removed. However during the second commit, the update for issue #333 was also included. Please let me know if I have to remove the changes and submit a separate PR or if it can stay the same. Thanks!

2021-10-07 03:09 UTC, geekygirlsarah requested changes
So I think if you make those changes, I'd merge this in. I realize it's a lot to undo, so sorry about that. (Though I do appreciate you thinking these parts through!)

2021-10-07 03:09 UTC, geekygirlsarah commented on web/thesauruses/_meta/operators.json
> +      "conditional_or_assignment",
For now, I'm going to say roll back all changes to `_meta/operators.json` as they need to be thought out more in issue #333 first before they're applied here. 

Similarly, remove the newer concept IDs (like `conditional_and`) from the C# file below so I can merge your PR but then we can edit the operators a little later after #333 is done.

2021-10-07 03:09 UTC, geekygirlsarah commented on web/thesauruses/csharp/operators.json
> +      "code": ""
YOu can remove `code` lines from anything that's `not-implemented: true`

2021-10-07 05:54 UTC, VaishnaviNandakumar commented
No worries! I've made the required changes. Since `_meta/operators.json` was updated with a few more operators  (unary plus, unary minus, integer division and integer division assignment) I added those too in `csharp/operators.json`. Do let me know if that's okay. Thanks.

2021-10-08 03:13 UTC, geekygirlsarah commented
Thanks for making the changes _*AND*_ adding the extra new operators in!

I'll merge this in then. I appreciate it!

2021-10-08 03:13 UTC, merged