Closes Issue 301 Haskell Math/Logic Operators
codethesaurus/codethesaur.us pull request #337
Opened 2021-10-07 02:06 UTC by RSid

## What GitHub issue does this PR apply to?

Resolves #301

## What changed and why?

Added the operators file for Haskell and filled out the relevant math and logic operators

## Checklist

- [x] I claimed any associated issue(s) and they are not someone else's
- [x] I have looked at documentation to ensure I made any revisions correctly
- [x] I tested my changes locally to ensure they work
- [ ] (If editing Django) I have added or edited any appropriate unit tests for my changes

## Any additional comments or things to be aware of while reviewing?

I'm new to Haskell and taking the opportunity to learn! Comments or corrections welcome.

2021-10-07 02:10 UTC, RSid commented on web/thesauruses/haskell/operators.json
> +      "code": "x^y, x^^y, x**y"
Not sure if this is the best way to format there being multiple correct operators

2021-10-07 02:10 UTC, RSid commented on web/thesauruses/haskell/operators.json
> +      "name": "Percentage operator",
Wasn't sure exactly what was meant by this? % is modulus in a lot of languages, but not in Haskell. It is a function to get the ratio of 2 integral numbers in the [Data.Ratio package](https://hackage.haskell.org/package/base-4.15.0.0/docs/Data-Ratio.html#v:-37-)

2021-10-07 02:10 UTC, RSid commented on web/thesauruses/haskell/operators.json
> +      "comment": "Haskell does not include bitwise operators by default, you need to import the Data.Bits module",
I went with the assumption I shouldn't include operators that aren't in the vanilla language installation with no imports, but let me know if I should include them and just document that you need to import Data.Bits for them to work.

2021-10-07 03:21 UTC, geekygirlsarah requested changes
This is good work so far! I appreciate you working on this as you learn Haskell. I'd be happy to merge it in after the changes. Feel free to ask me if you have any more questions!

2021-10-07 03:21 UTC, geekygirlsarah commented on web/thesauruses/haskell/operators.json
> +    "language": "language_id",
This line should be `"haskell"`

2021-10-07 03:21 UTC, geekygirlsarah commented on web/thesauruses/haskell/operators.json
> +      "code": "",
You can remove `code` lines from any `not-implemented` section.

2021-10-07 03:21 UTC, geekygirlsarah commented on web/thesauruses/haskell/operators.json
> +      "name": "Addition operator",
You can delete all the `name` lines as they aren't read in from these files.

2021-10-07 03:21 UTC, geekygirlsarah commented on web/thesauruses/haskell/operators.json
> +      "code": "x^y, x^^y, x**y"
To help make code blocks technically compileable, I've been suggesting putting each one on a new line (so adding `\n` between each for each new line), and then in the comments showing they're separate ways to do it (which you already have in the comments).

2021-10-07 03:21 UTC, geekygirlsarah commented on web/thesauruses/haskell/operators.json
> +      "name": "Percentage operator",
In this case, just call it `not-implemented` and it's good. If it requires outside packages, I've not really had people add those in.

2021-10-07 03:21 UTC, geekygirlsarah commented on web/thesauruses/haskell/operators.json
> +      "code": "x /= y, \nnot x"
Same here for the multiple ways of doing it, add a `\n` between them and add a comment to say there's multiple ways to do it.

2021-10-07 03:21 UTC, geekygirlsarah commented on web/thesauruses/haskell/operators.json
> +      "comment": "Haskell does not include bitwise operators by default, you need to import the Data.Bits module",
I've generally stuck with vanilla language things, so you can leave this out. If `Data.Bits` is built-in, you could include it. Either way. Just if you do include it, maybe add a comment or code line for the import statement.

2021-10-07 22:39 UTC, RSid commented on web/thesauruses/haskell/operators.json
> +      "comment": "Haskell does not include bitwise operators by default, you need to import the Data.Bits module",
I'll go ahead and include it with the import & comment, since it's built-in - seems nice to err on the side of completeness

2021-10-07 22:54 UTC, RSid commented
> This is good work so far! I appreciate you working on this as you learn Haskell. I'd be happy to merge it in after the changes. Feel free to ask me if you have any more questions!

Thank you! And thanks for the speedy review, I think I've addressed your comments. Let me know if anything else jumps out at you!

2021-10-08 04:50 UTC, geekygirlsarah approved these changes

2021-10-08 04:54 UTC, geekygirlsarah commented
> 
> Thank you! And thanks for the speedy review, I think I've addressed your comments. Let me know if anything else jumps out at you!

I do _TRY_ to review them fast. I've been trying even more because a ton of people found this project recently and it's a LOT of work to review that many! 

And the new changes look good. I'll merge it. Don't forget to sign up for Hacktoberfest if you're wanting the shirt as this counts for that!

2021-10-08 04:54 UTC, merged