Php Lists added Resolves #289
codethesaurus/codethesaur.us pull request #340
Opened 2021-10-07 09:02 UTC by alexindris

## What GitHub issue does this PR apply to?

Resolves #289 

## What changed and why?

list.json php implementing Arrays l ists and hashes

## Checklist

- [x] I claimed any associated issue(s) and they are not someone else's
- [x] I have looked at documentation to ensure I made any revisions correctly
- [x] I tested my changes locally to ensure they work
- [ ] (If editing Django) I have added or edited any appropriate unit tests for my changes

## Any additional comments or things to be aware of while reviewing?

2021-10-08 04:30 UTC, geekygirlsarah requested changes
I think with a few changes and fixing some typos, this will be good to merge!

2021-10-08 04:30 UTC, geekygirlsarah commented on web/thesauruses/php/lists.json
> +      "code": "",
For concepts that aren't implemented, can you remove the `code` line? it just helps clean up the file some.

2021-10-08 04:30 UTC, geekygirlsarah commented on web/thesauruses/php/lists.json
> +    "do_two_lists_match_exactly": {
doesn't array_diff return an array of different items? I think this (and `do_two_lists_contain_same_items`) are both boolean-based concepts

2021-10-08 04:30 UTC, geekygirlsarah commented on web/thesauruses/php/lists.json
> +      "comment": "Sorttipe is optional\n possible values are\n0 = SORT_REGULAR - Default. Compare items normally (don't change types) \n 1 = SORT_NUMERIC - Compare items numerically\n2 = SORT_STRING
Did you mean "Sort type is optional"?

2021-10-08 04:30 UTC, geekygirlsarah commented on web/thesauruses/php/lists.json
> +      "code": "suffle($array)"
Should this be `shuffle($array)` ?

2021-10-08 06:13 UTC, alexindris commented on web/thesauruses/php/lists.json
> +      "comment": "Sorttipe is optional\n possible values are\n0 = SORT_REGULAR - Default. Compare items normally (don't change types) \n 1 = SORT_NUMERIC - Compare items numerically\n2 = SORT_STRING
Yes the sort type is optional in order to be able to choose between diferent ways

2021-10-08 06:15 UTC, alexindris commented on web/thesauruses/php/lists.json
> +      "code": "suffle($array)"
Yes it is

2021-10-10 04:48 UTC, geekygirlsarah commented on web/thesauruses/php/lists.json
> +      "comment": "Sorttipe is optional\n possible values are\n0 = SORT_REGULAR - Default. Compare items normally (don't change types) \n 1 = SORT_NUMERIC - Compare items numerically\n2 = SORT_STRING
I was pointing out the typo, but you got it.

2021-10-10 04:52 UTC, geekygirlsarah commented
I think you fixed the issues, so I'll merge this in!

Thank you for adding this! Don't forget to sign up for Hacktoberfest if you haven't already since this counts!

2021-10-10 04:52 UTC, merged