Added Logic/Math Operators for Objective-C
codethesaurus/codethesaur.us pull request #341
Opened 2021-10-07 09:31 UTC by riyakushwaha

## What GitHub issue does this PR apply to?

Resolves #305

## What changed and why?
Added operators.json in web/thesauruses/objective-c folder 

## (If editing Django app) Please add screenshots
No changes

## Checklist

- [ ] I claimed any associated issue(s) and they are not someone else's
- [ ] I have looked at documentation to ensure I made any revisions correctly
- [ ] I tested my changes locally to ensure they work
- [ ] (If editing Django) I have added or edited any appropriate unit tests for my changes

## Any additional comments or things to be aware of while reviewing?

2021-10-08 04:35 UTC, geekygirlsarah requested changes
I think this is close! Make the couple of changes and it should be good to merge!

2021-10-08 04:35 UTC, geekygirlsarah commented on web/thesauruses/objectivec/operators.json
> +      "code": "",
If a concept is `not-implemented`, you can remove the `code` line. (And for all of the ones below)

2021-10-08 04:35 UTC, geekygirlsarah commented on web/thesauruses/objectivec/operators.json
> +      "comment": "Shits the specified bits to left, so a equals to (4)100"
Uh... I think this is a typo 😂

2021-10-08 07:43 UTC, riyakushwaha commented
Thanks for reviewing. I have made all the required changes and made a pull request. Kindly have a look.

2021-10-10 04:59 UTC, geekygirlsarah requested changes

2021-10-10 04:59 UTC, geekygirlsarah commented on web/thesauruses/objectivec/operators.json
> +      "comment": "Shits the specified bits to left, so a equals to 4"
You still have a typo with "shift" here

2021-10-10 11:33 UTC, riyakushwaha commented on web/thesauruses/objectivec/operators.json
> +      "comment": "Shits the specified bits to left, so a equals to 4"
Soory I missed this again. I have corrected it now.

2021-10-13 00:45 UTC, geekygirlsarah commented
Thanks for that last change! I'll merge it in.

Don't forget to sign up for Hacktoberfest if you haven't and if you want the shirt/stickers!

2021-10-13 00:45 UTC, merged