Added lists/arrays/hash list concepts for Typescript #295
codethesaurus/codethesaur.us pull request #345
Opened 2021-10-08 10:54 UTC by abhishek7997

## What GitHub issue does this PR apply to?

Resolves #295 

## What changed and why?

lists.json file is added under the typescript directory, with the required changes.

## (If editing Django app) Please add screenshots

## Checklist

- [X] I claimed any associated issue(s) and they are not someone else's
- [X] I have looked at documentation to ensure I made any revisions correctly
- [X] I tested my changes locally to ensure they work
- [ ] (If editing Django) I have added or edited any appropriate unit tests for my changes

## Any additional comments or things to be aware of while reviewing?

Please clarify the difference between "Do two lists match every element?" and "Do two lists contain all the same items?".
I think they mean the same thing.

2021-10-10 05:16 UTC, geekygirlsarah requested changes

2021-10-10 05:16 UTC, geekygirlsarah commented on web/thesauruses/typescript/lists.json
> +      "code": "Syntax: let arrayName: type[];\nExamples: \nlet scores : (string | number)[];\nlet nums : number[] = [12.34,1,2,3];\nlet arr : Array<any> = [1,2,3,'hi'];\nlet arr : Array<number|boolea
The `code` lines should be for actual compileable code. I get what you're doing, but if you want to explain things or mention examples, they should go in a `comment` and leave the `code` for the part that's valid TypeScript. The exception  might be if there's more than one way to do it, then maybe differentiate them in either `comment` or with a comment within the `code`.

2021-10-10 05:16 UTC, geekygirlsarah commented on web/thesauruses/typescript/lists.json
> +      "comment": "In strict mode, use of delete keyword on simple data is prohibited"
You refer to the delete keyword can't be used in strict mode, but what about the un-strict mode? Is there a delete keyword for that? If there's two ways to do it, you can show both, just comment what's going on.

2021-10-10 05:18 UTC, abhishek7997 commented on web/thesauruses/typescript/lists.json
> +      "comment": "In strict mode, use of delete keyword on simple data is prohibited"
Ok

2021-10-10 05:23 UTC, geekygirlsarah requested changes

2021-10-10 05:23 UTC, geekygirlsarah commented on web/thesauruses/typescript/lists.json
> +      "code": "",
For `not-implemented` lines, could you delete the empty `code` so it cleans it up a bit?

2021-10-10 05:23 UTC, geekygirlsarah commented on web/thesauruses/typescript/lists.json
> +      "comment": "There is no inbuilt function that takes an index and returns two arrays"
Typically, if there's not a built-in way to do something, then I'd just leave it as a `not-implemented: true` type thing. However, this now has me wondering if it's a simple solution (like your two lines here), maybe I should allow these? I wanted Code Thesaurus to really have simple, built-in replacements but maybe this is fine. 🤔

2021-10-10 05:24 UTC, geekygirlsarah commented
This is pretty good! I appreciate the work. Make the minor change and I can probably merge it in. (And thanks for giving me something to think about with whether to allow only built-in functions or small, sort solutions to similar things.)

2021-10-10 05:33 UTC, abhishek7997 commented
> This is pretty good! I appreciate the work. Make the minor change and I can probably merge it in. (And thanks for giving me something to think about with whether to allow only built-in functions or small, sort solutions to similar things.)

Newline '\n' is not working in comment.
![image](https://user-images.githubusercontent.com/68701271/136683690-8d3ef491-a270-432c-babb-7ccdaa026c7c.png)

"create_a_unordered_mutable_list": {
      "code": "let arrayName: type[];",
      "comment": "Examples: let scores : (string | number)[];\nlet nums : number[] = [12.34,1,2,3];\nlet arr : Array<any> = [1,2,3,'hi'];\nlet arr : Array<number|boolean> = [1, true, 2];"
    },

2021-10-10 05:34 UTC, abhishek7997 commented on web/thesauruses/typescript/lists.json
> +      "comment": "In strict mode, use of delete keyword on simple data is prohibited"
I tried in unstrict mode, but I found that the entire array cannot be deleted using the 'delete' keyword, another way is to set arrayName to undefined.

2021-10-10 06:50 UTC, abhishek7997 commented
Please check my updated PR. @geekygirlsarah

2021-10-12 15:52 UTC, abhishek7997 commented
Please check my updated PR. @geekygirlsarah

2021-10-12 16:11 UTC, geekygirlsarah commented
> 
> 
> Please check my updated PR. @geekygirlsarah

I'm just one maintainer and this is my side project. I also have a lot of other life activities going on. I'm addressing the PRs and comments in the order they come in. I'll get to yours, just please be patient.

2021-10-12 16:12 UTC, abhishek7997 commented
> > Please check my updated PR. @geekygirlsarah
> 
> I'm just one maintainer and this is my side project. I also have a lot of other life activities going on. I'm addressing the PRs and comments in the order they come in. I'll get to yours, just please be patient.

Okay.

2021-10-13 02:46 UTC, geekygirlsarah commented
> Newline '\n' is not working in comment. ![image](https://user-images.githubusercontent.com/68701271/136683690-8d3ef491-a270-432c-babb-7ccdaa026c7c.png)

Thanks for pointing this out! I made issue #362 to fix it!

You can leave in the `\n` and it'll eventually work when the bug is fixed. (If someone doesn't grab it, maybe I'll do it this week as it shoudl be simple.)

2021-10-13 02:55 UTC, geekygirlsarah requested changes

2021-10-13 02:55 UTC, geekygirlsarah commented on web/thesauruses/typescript/lists.json
> +      "code": "Syntax: let arrayName: type[];\nExamples: \nlet scores : (string | number)[];\nlet nums : number[] = [12.34,1,2,3];\nlet arr : Array<any> = [1,2,3,'hi'];\nlet arr : Array<number|boolea
You still have uncompileable code here. Please keep `code` to just `let arrayName: type[];` and use examples or other comments in a `comment` line you need to add.

2021-10-20 05:26 UTC, geekygirlsarah commented on web/thesauruses/typescript/lists.json
> +      "code": "Syntax: let arrayName: type[];\nExamples: \nlet scores : (string | number)[];\nlet nums : number[] = [12.34,1,2,3];\nlet arr : Array<any> = [1,2,3,'hi'];\nlet arr : Array<number|boolea
I'm still waiting on this part to get fixed. I think I can merge it in if you wrap this up.

2021-10-20 05:33 UTC, abhishek7997 commented on web/thesauruses/typescript/lists.json
> +      "code": "Syntax: let arrayName: type[];\nExamples: \nlet scores : (string | number)[];\nlet nums : number[] = [12.34,1,2,3];\nlet arr : Array<any> = [1,2,3,'hi'];\nlet arr : Array<number|boolea
@geekygirlsarah I have already made the changes. Please check my latest commit.

![image](https://user-images.githubusercontent.com/68701271/138033987-c67ecd84-7b15-44da-8e98-64be92290fe3.png)

![image](https://user-images.githubusercontent.com/68701271/138034096-b7502156-7e8b-460b-82bf-dcc639575ffc.png)

2021-10-21 03:09 UTC, abhishek7997 commented
@geekygirlsarah I need some help. I think I may have pushed too many commits. I got confused as to what branch I should push from. Can you please delete/merge those last 4 commits?

2021-10-22 15:15 UTC, abhishek7997 commented
@geekygirlsarah Please check my PR. From my end everything looks alright.

2021-10-23 05:48 UTC, geekygirlsarah commented
> 
> 
> @geekygirlsarah I need some help. I think I may have pushed too many commits. I got confused as to what branch I should push from. Can you please delete/merge those last 4 commits?

I can't remove commits as they are on your branch and I don't have access to it. Only you can do it and would probably have to force-push it after resetting or re-committing or something. I'm not worried about it as the PR says ultimately you're changing one file and the file looks correct.

I'll merge it in. Thank you!

2021-10-23 05:48 UTC, merged

2021-10-23 06:10 UTC, abhishek7997 commented
> > @geekygirlsarah I need some help. I think I may have pushed too many commits. I got confused as to what branch I should push from. Can you please delete/merge those last 4 commits?
> 
> I can't remove commits as they are on your branch and I don't have access to it. Only you can do it and would probably have to force-push it after resetting or re-committing or something. I'm not worried about it as the PR says ultimately you're changing one file and the file looks correct.
> 
> I'll merge it in. Thank you!

Okay. Thank s.