feat: add opengraph to views
codethesaurus/codethesaur.us pull request #348
Opened 2021-10-09 02:31 UTC by lukeberry99

## What GitHub issue does this PR apply to?

Resolves #135

## What changed and why?

Added opengraph for improved SEO

## Checklist

- [x] I claimed any associated issue(s) and they are not someone else's
- [x] I have looked at documentation to ensure I made any revisions correctly
- [x] I tested my changes locally to ensure they work
- [ ] (If editing Django) I have added or edited any appropriate unit tests for my changes

## Any additional comments or things to be aware of while reviewing?

No unit tests have been added because I can't find a way to test that the meta tags have been rendered inside the view with the current testing setup, I'm happy to create a new issue for adding additional testing functionality and to start working on implementing that.

2021-10-10 05:31 UTC, geekygirlsarah commented
Nice! I like it. Just fix the minor wording and I'll merge it in!

2021-10-14 09:35 UTC, lukeberry99 commented
Hi @geekygirlsarah I can't see any comments / review for wording changes, can you let me know what you'd like changed and I'll get that done for you asap.

Cheers

2021-10-15 05:06 UTC, geekygirlsarah requested changes
With Github's review comments, I sometimes forget to hit "submit review" when I'm done. So it was just "pending" this whole time and never sent to you. Sorry about that. 😬

2021-10-15 05:06 UTC, geekygirlsarah commented on web/views.py
> +        "description": "Code Thesaurus: Comparing " + lang1.friendly_name + " " + lang2.friendly_name
Could you add `and` between the languages? Otherwise it'll be like "Comparing Ruby Python" which doesn't make sense.

2021-10-15 07:52 UTC, lukeberry99 commented
@geekygirlsarah no worries! I've also added the 'and' to the title above, as it had the same problem.

2021-10-15 14:48 UTC, geekygirlsarah commented on web/views.py
> +        "description": "Code Thesaurus: Comparing " + lang1.friendly_name + " " + lang2.friendly_name
I kind of love that you figured this out before I left the comment, lol

2021-10-15 14:52 UTC, geekygirlsarah commented
This is great, thank you for doing this! I'll merge it in.

Don't forget to sign up for Hacktoberfest as this can count towards the shirt/swag!

2021-10-15 14:52 UTC, merged