Add Objective-C Lists/Arrays
codethesaurus/codethesaur.us pull request #349
Opened 2021-10-09 09:24 UTC by vinayak0127

## What GitHub issue does this PR apply to?

Resolves #288 

## What changed and why?

## (If editing Django app) Please add screenshots

## Checklist

- [x] I claimed any associated issue(s) and they are not someone else's
- [x] I have looked at the documentation to ensure I made any revisions correctly
- [x] I tested my changes locally to ensure they work
- [ ] (If editing Django) I have added or edited any appropriate unit tests for my changes

## Any additional comments or things to be aware of while reviewing?

2021-10-10 14:16 UTC, geekygirlsarah commented on web/thesauruses/objectivec/lists.json
> +      "code": "NSMutable *fullName = [NSMutableArray arrWtihObj: @\"Jack\",@\"Sparrow\",nil]"
"Jack Sparrow" 😂

2021-10-10 14:23 UTC, geekygirlsarah requested changes
There's a couple of questions and comments, but this is close to ready!

2021-10-10 14:23 UTC, geekygirlsarah commented on web/thesauruses/objectivec/lists.json
> +      "code": "insert(_:at:) - Inserts a given object into the array’s contents at a given index."
I appreciate the definition, but the `code` line should be compileable code. Any comments or explanations should go in a `comment` line.

(Same for the lines below too)

2021-10-10 14:23 UTC, geekygirlsarah commented on web/thesauruses/objectivec/lists.json
> +      "comment": "addObject: - Adds a given object to the set, if it is not already a member."
You have `not-implemented` here, but then you have a comment that sounds like this actually exists. Can you clarify? 

(You do this a few times below too)

2021-10-10 14:23 UTC, geekygirlsarah commented on web/thesauruses/objectivec/lists.json
> +    },
Is this not implemented? It should be set and the `code` line removed

2021-10-10 16:36 UTC, vinayak0127 commented on web/thesauruses/objectivec/lists.json
> +      "comment": "addObject: - Adds a given object to the set, if it is not already a member."
There is no actual function that is used to insert in the middle, addObject is used to insert at any index generally.
that's why I wrote that comment.

2021-10-10 16:37 UTC, vinayak0127 commented on web/thesauruses/objectivec/lists.json
> +      "code": "insert(_:at:) - Inserts a given object into the array’s contents at a given index."
Okay, I'll keep that in mind.

2021-10-10 16:44 UTC, vinayak0127 commented on web/thesauruses/objectivec/lists.json
> +      "code": "NSMutable *fullName = [NSMutableArray arrWtihObj: @\"Jack\",@\"Sparrow\",nil]"
Hey, should i change it ?😂

2021-10-11 17:37 UTC, vinayak0127 commented on web/thesauruses/objectivec/lists.json
> +    },
yes, I'll remove it.

2021-10-13 02:26 UTC, geekygirlsarah commented on web/thesauruses/objectivec/lists.json
> +      "code": "NSMutable *fullName = [NSMutableArray arrWtihObj: @\"Jack\",@\"Sparrow\",nil]"
Nah, I was amused!

2021-10-13 02:38 UTC, geekygirlsarah requested changes
I think there's still a few more changes. You're close. If you can fix these things, I can merge it in.

2021-10-13 02:38 UTC, geekygirlsarah commented on web/thesauruses/objectivec/lists.json
> +      "code": "insert(_:at:) - Inserts a given object into the array’s contents at a given index."
Well, I was hoping you'd update them, or better yet, delete them. So `"code": "insert(_:at:)"` and `"comment": "Inserts a given object..."`  (or actually leave off `comment` all together). 

(See:  https://codethesauru-main-uzk96crhjcxu.herokuapp.com/reference/?concept=lists&lang=objectivec and how it's redundant.)

![image](https://user-images.githubusercontent.com/2601974/137056880-efd8aa54-fdde-44a9-bc0f-98da47318c47.png)

2021-10-13 02:38 UTC, geekygirlsarah commented on web/thesauruses/objectivec/lists.json
> +      "comment": "addObject: - Adds a given object to the set, if it is not already a member."
I guess to clarify on this more, this is a concept that's a question. CAN you insert something in the middle of a mutable list? So it should really just be yes/no, not the name of a function.

![image](https://user-images.githubusercontent.com/2601974/137057377-3cf16a05-19c1-464e-a6ed-e1907ccf08e0.png)

2021-10-19 16:09 UTC, vinayak0127 commented
hey @geekygirlsarah  can you review new changes?

2021-10-19 16:21 UTC, geekygirlsarah commented
Hi @vinayak0127. I am the only maintainer on this, and I also have a day job and side activities. I am assinging issues, answering comments, and reviewing and approving PRs, but I am busy and working on Code Thesaurus is not my main job. So I need patience as I am reviewing things in the order they come in. I will get to this, you just have to wait.

2021-10-20 05:30 UTC, geekygirlsarah commented
Alright, I think the changes look good and it's ready to be merged.

Thank you for working on another issue on this and for making the suggested changes!

2021-10-20 05:30 UTC, merged