Issue 309 add rust logical and math operators
codethesaurus/codethesaur.us pull request #354
Opened 2021-10-10 18:29 UTC by bug-author

## What GitHub issue does this PR apply to?

Resolves #309 

## What changed and why?

Added Logical and Math operators for Rust 

## (If editing Django app) Please add screenshots

## Checklist

- [X] I claimed any associated issue(s) and they are not someone else's
- [X] I have looked at documentation to ensure I made any revisions correctly
- [x] I tested my changes locally to ensure they work
- [ ] (If editing Django) I have added or edited any appropriate unit tests for my changes

## Any additional comments or things to be aware of while reviewing?

I renamed my branch to fix a typo before pushing the final commit, I guess that's the reason GitHub is showing commits as if they are from multiple users in this PR.

2021-10-13 02:15 UTC, geekygirlsarah requested changes
I think the two small changes and this is good to merge!

2021-10-13 02:15 UTC, geekygirlsarah commented on web/thesauruses/rust/operators.json
> +      "comment": "Rust provides methods pow and checked_pow for exponentiation."
could you give an example of both? Sounds like it's implemented as a function rather than an operator (but it'll work in this case)

2021-10-13 02:15 UTC, geekygirlsarah commented on web/thesauruses/rust/operators.json
> +      "comment": "Rust provides abs method for finding absolute value."
Same for `abs` here.

2021-10-13 06:12 UTC, bug-author commented on web/thesauruses/rust/operators.json
> +      "comment": "Rust provides methods pow and checked_pow for exponentiation."
Sure. Just to make it clear, I should remove the `not-implemented` key and provide both examples as a part of `code`?

2021-10-13 13:51 UTC, geekygirlsarah commented on web/thesauruses/rust/operators.json
> +      "comment": "Rust provides methods pow and checked_pow for exponentiation."
Yeah. I don't know the difference between the two but if they both serve some form of doing exponentials, then I'd like to have them here! Despite this being operators, I don't know that I imagine any other place to put functions like that in CT.

2021-10-13 15:50 UTC, bug-author commented
@geekygirlsarah I've made the changes as per the requirements.

2021-10-15 05:04 UTC, geekygirlsarah commented on web/thesauruses/rust/operators.json
> +      "comment": "Rust provides methods pow and checked_pow for exponentiation."
To the best of my knowledge, `code` only is a string, not an array/list. Did you test this to confirm it works still?

2021-10-15 15:22 UTC, bug-author commented on web/thesauruses/rust/operators.json
> +      "comment": "Rust provides methods pow and checked_pow for exponentiation."
I have now added both methods as a single string separated by comma, and tested the code.

I was confused as there were two methods that's why I asked if I should provide both of them as a part of `code`. There are no multi-line strings allowed in JSON, so arrays seemed semantically they correct way for two different entities belonging to one key. I should have tested the code after making changes, I'm so sorry.

2021-10-15 16:15 UTC, geekygirlsarah commented on web/thesauruses/rust/operators.json
> +      "comment": "Rust provides methods pow and checked_pow for exponentiation."
Typically people have added `\n` to separate out new lines in JSON strings, which is probably what I'd prefer here.

And yeah, an array/list does tend to make sense, but that's sort of where looking over docs or seeing how others do it would come in handy. It might be a thing we can add, but it's not how the system works presently (though, like I said, I never tested it so I'm not sure what it would do).

2021-10-15 17:06 UTC, bug-author commented on web/thesauruses/rust/operators.json
> +      "comment": "Rust provides methods pow and checked_pow for exponentiation."
I've made the changes and tested with `\n`. Once again, I apologize for being hasty and not looking into docs - I'm going through them now!

I'm a newbie dev so I might be wrong, but I think the array/ list approach would result in better readability - presently it does not work I tested it.

2021-10-17 05:24 UTC, geekygirlsarah commented
> 
> 
> @geekygirlsarah I've made the changes as per the requirements.

For future reference, you can always click "Resolve conversation" to notify the maintainer you've made the changes on a PR.

Also I think it looks better. I'll merge it in.

Thanks! This counts towards Hacktoberfest, so be sure to sign up if you want this to count towards the shirt/swag!

2021-10-17 05:24 UTC, merged