added php classes
codethesaurus/codethesaur.us pull request #355
Opened 2021-10-11 14:59 UTC by apoorvpal01

## What GitHub issue does this PR apply to?

Resolves #272 

## What changed and why?

Added JSON formatted information for PHP Classes.

## (If editing Django app) Please add screenshots

## Checklist

- [x] I claimed any associated issue(s) and they are not someone else's
- [x] I have looked at documentation to ensure I made any revisions correctly
- [x] I tested my changes locally to ensure they work
- [x] (If editing Django) I have added or edited any appropriate unit tests for my changes

## Any additional comments or things to be aware of while reviewing?

2021-10-13 02:18 UTC, geekygirlsarah requested changes
Practically there! Make the minor changes, and I'll merge this in!

2021-10-13 02:18 UTC, geekygirlsarah commented on web/thesauruses/php/classes.json
> +      "language_name": "Human-Friendly Language Name"
Can you update these to `php`, whatever major/minor version is the latest (7.4?), and `PHP`?

2021-10-13 02:18 UTC, geekygirlsarah commented on web/thesauruses/php/classes.json
> +        "code": "",
You can remove all `code` lines for anything that's not implemented.

2021-10-13 04:40 UTC, apoorvpal01 commented on web/thesauruses/php/classes.json
> +      "language_name": "Human-Friendly Language Name"
I have added the language data in a new commit. The current stable version is `8.0`

2021-10-13 04:41 UTC, apoorvpal01 commented on web/thesauruses/php/classes.json
> +        "code": "",
I have added a commit removing the code lines from features that are not implemented.

2021-10-15 04:45 UTC, geekygirlsarah approved these changes

2021-10-15 04:48 UTC, geekygirlsarah commented
Thank you for the changes! I think it's ready for merging.

Don't forget to sign up for Hacktoberfest if you want this to count towards the shirt/swag!

2021-10-15 04:48 UTC, merged