Increased Lighthouse scores (Issue #346)
codethesaurus/codethesaur.us pull request #361
Opened 2021-10-12 22:47 UTC by splashley

## What GitHub issue does this PR apply to?

Resolves #346 

## What changed and why?

Prior to this fix, these were the Lighthouse scores:
Performance: 93
Accessibility: 77
Best Practices: 87
SEO: 100

Now they are:
Performance: 97
Accessibility: 100
Best Practices: 93
SEO: 100

- Removed all self-hosted Bootstrap and Fontawesome files.
- Resolved some accessibility issues

## Checklist

- [X] I claimed any associated issue(s) and they are not someone else's
- [X] I have looked at documentation to ensure I made any revisions correctly
- [X] I tested my changes locally to ensure they work
- [ ] (If editing Django) I have added or edited any appropriate unit tests for my changes

## Any additional comments or things to be aware of while reviewing?

N/A

2021-10-12 23:44 UTC, geekygirlsarah requested changes
I think this is the only issue I've seen. I can probably merge it after you fix this!

2021-10-12 23:44 UTC, geekygirlsarah commented on web/templates/base.html
> +<script src="../" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
I'm confused... what's the `src` for this? looks like you deleted something extra on here. (was this the old bootstrap? Should the line be deleted? also the `app.js` line is gone? I guess the app.js file is empty so that's fine, but maybe we could delete app.js too?)

2021-10-13 13:10 UTC, splashley commented on web/templates/base.html
> +<script src="../" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
I removed line 77 and replaced it with an updated version of Bootstrap.
I'll delete app.js as well.

2021-10-13 22:13 UTC, geekygirlsarah commented
Sweet, that works. Thank you! I'll merge it in!

And sign up for Hacktoberfest! You're now halfway to getting the shirt/swag!

2021-10-13 22:13 UTC, merged