Added lists/arrays/hashes for go
codethesaurus/codethesaur.us pull request #373
Opened 2021-10-17 08:29 UTC by Skr-suyash

## What GitHub issue does this PR apply to?

Resolves #284

## What changed and why?

Added the Lists/Arrays/Hashes concept for Go language.

## (If editing Django app) Please add screenshots

## Checklist

- [x] I claimed any associated issue(s) and they are not someone else's
- [x] I have looked at documentation to ensure I made any revisions correctly
- [x] I tested my changes locally to ensure they work
- [ ] (If editing Django) I have added or edited any appropriate unit tests for my changes

## Any additional comments or things to be aware of while reviewing?

2021-10-20 00:42 UTC, samuelburns commented
Did this run properly when you ran it in the container? Mine didn't for swift

2021-10-20 03:37 UTC, Skr-suyash commented
I tested it using django webserver and it was running fine.

![Screenshot (36)](https://user-images.githubusercontent.com/43753331/138024264-8def83aa-ddf8-45e1-9a19-7918e1efc5fc.png)

Let me test for the container too.

2021-10-23 04:58 UTC, geekygirlsarah commented
> 
> 
> Did this run properly when you ran it in the container? Mine didn't for swift

This can be tested at https://codethesaurus-pr-373.herokuapp.com

2021-10-23 05:27 UTC, geekygirlsarah requested changes
A few quick, minor things and I think this could be good to merge.

2021-10-23 05:27 UTC, geekygirlsarah commented on web/thesauruses/go/lists.json
> +      "name": "What is a ordered, mutable list called?",
You can delete all the `name` fields as they're pulled from the meta language file.

2021-10-23 05:27 UTC, geekygirlsarah commented on web/thesauruses/go/lists.json
> +      "code": "",
To help clean it up more, you can remove the `code` line when things aren't implemented in the language.

2021-10-23 05:27 UTC, geekygirlsarah commented on web/thesauruses/go/lists.json
> +      "code": ""
You might have missed this one. Is there code or is it `not-implemented`?

2021-10-23 11:41 UTC, Skr-suyash commented on web/thesauruses/go/lists.json
> +      "name": "What is a ordered, mutable list called?",
Done...

2021-10-23 11:42 UTC, Skr-suyash commented on web/thesauruses/go/lists.json
> +      "code": ""
Done...

2021-10-23 11:42 UTC, Skr-suyash commented
Completed all the changes that were expected.

2021-10-23 21:19 UTC, geekygirlsarah commented on web/thesauruses/go/lists.json
> +      "code": "for i := 0; i < len(numbers)/2; i++ {\n    j := len(numbers) - i - 1\n    numbers[i], numbers[j] = numbers[j], numbers[i]\n}"
I see what you're trying to do here, but if it's not a built-in function, it should just be "not implemented"

2021-10-24 08:09 UTC, Skr-suyash commented
Removed the requested code. Go offers the bare minimum with its data structures, so I thought to include those. 😅

2021-10-25 22:29 UTC, geekygirlsarah commented
Uh oh... I think you took out the algorithm AND the built-in libraries... 😬

I was trying to keep CT to the built-in stuff. Standard Libraries are built-in stuff. Third-party libraries are not, and writing algorithms are not.

Would it be terrible if you added those back in? You could probably cherry-pick from one of your old commits.

![image](https://user-images.githubusercontent.com/2601974/138779587-16f00e54-9e05-4bfd-a30c-4ce03fe4f600.png)

2021-10-26 17:03 UTC, Skr-suyash commented
This means I should remove only that self implemented reverse algorithm and add the standard libraries back up.
Sorry for the trouble, I got a bit confused.

2021-10-26 17:08 UTC, Skr-suyash commented
Kindly review the latest commit.

2021-10-29 14:03 UTC, geekygirlsarah commented
I think it looks good @Skr-suyash ! I'll merge it in. Thank you for working on this!

2021-10-29 14:03 UTC, merged