fix link to readme
codethesaurus/codethesaur.us pull request #377
Opened 2021-10-18 23:04 UTC by tealjulia

## What GitHub issue does this PR apply to?

N/A

## What changed and why?

There was a broken link in the docs to the project README.md

## (If editing Django app) Please add screenshots

## Checklist

- [x] I claimed any associated issue(s) and they are not someone else's
- [x] I have looked at documentation to ensure I made any revisions correctly
- [x] I tested my changes locally to ensure they work
- [x] (If editing Django) I have added or edited any appropriate unit tests for my changes

## Any additional comments or things to be aware of while reviewing?

2021-10-20 05:04 UTC, geekygirlsarah requested changes
I think if you fix the README link, this will be good to merge!

2021-10-20 05:04 UTC, geekygirlsarah commented on CONTRIBUTING.md
> +1. Make sure you test the changes. Check out how to run the project on the [`README.md`](https://github.com/codethesaurus/codethesaur.us/README.md) page.
This link gave me a "Not found" error.  I think you want https://github.com/codethesaurus/codethesaur.us/blob/main/README.md .

2021-10-30 17:35 UTC, geekygirlsarah commented
Hey @tealjulia, I figured I'd check in on this since it's been over a week since the last comment. Have any questions or need anything?

2021-11-01 14:32 UTC, tealjulia commented
Ah, no, just got distracted :)

2021-11-01 23:20 UTC, geekygirlsarah commented
That works. Thank you! I'll merge it!

2021-11-01 23:20 UTC, merged