Merge views
codethesaurus/codethesaur.us pull request #598
Opened 2022-10-17 21:20 UTC by cafce25

Since we can't reopen #469

2022-11-10 05:08 UTC, geekygirlsarah requested changes

2022-11-10 05:08 UTC, geekygirlsarah commented on web/templates/concepts.html
> +                    languages.</p>
"two languages" is fine for comparing but not the reference.

2022-11-10 05:08 UTC, geekygirlsarah commented on web/templates/concepts.html
> +                </p>
Similarly there might be one/two links depending on if they do a compare/reference.

2022-11-10 05:19 UTC, geekygirlsarah commented
I have a couple of problems with this PR.

It starts off acting like a refactor (via removing deduplication). I'm here for that, let's do it.

Though you also add in extra classes and move code around. The error checking for files existing and all that probably didn't need to move but it's a bit more clear with Exceptions, so I'm ok with that.

But you also rename several variables. Well, ok, also in the sake of clarity I'm ok with this.

At this point the PR has a lot happening and is starting to get confusing and probably shouldn't be so large for something not really discussed previously. Or at least it should have stopped here.

But you also removed the URL paths, which wasn't really discussed either. And I get why you did it, but in turn it does make it more difficult to add in new comparisons of different things if there's no paths anymore. If you're going that route, I'd probably prefer to keep it at `/compare` or `/languages/` or something and it can take 1 or 2 languages and as the longer term vision aspects of CT get added, we can add more paths to account for it. The other thing is I'd probably rather have a URL like `/compare/lang1/lang2/` rather than `/?lang=one&lang=two` as it's a bit more SEO friendly and looks cleaner.

2022-11-11 09:41 UTC, cafce25 commented
> But you also removed the URL paths, which wasn't really discussed either. And I get why you did it, but in turn it does make it more difficult to add in new comparisons of different things if there's no paths anymore. If you're going that route, I'd probably prefer to keep it at `/compare` or `/languages/` or something and it can take 1 or 2 languages and as the longer term vision aspects of CT get added, we can add more paths to account for it. The other thing is I'd probably rather have a URL like `/compare/lang1/lang2/` rather than `/?lang=one&lang=two` as it's a bit more SEO friendly and looks cleaner.

Definitely with you on paths vs GET parameters.
Should I just change the links to go to the old routes and we worry about changing urls later?
If I do that should I leave in the code that renders concepts on the index page if it receives parameters?

2022-11-14 03:17 UTC, geekygirlsarah commented
> Definitely with you on paths vs GET parameters.

Great!

> Should I just change the links to go to the old routes and we worry about changing urls later? 

Yeah, let's not modify the URLs yet. That should probably be its own issue and thinking through how that will work.

> If I do that should I leave in the code that renders concepts on the index page if it receives parameters?

Yeah, that's probably fine, though it'll probably have to get removed when adding in future things that CT is comparing as it query strings on `/` won't necessarily work on other topics. But don't know that anyone is doing this presently, so I'm not sure that it benefits anything by staying in either.

(Don't know if you've seen https://github.com/orgs/codethesaurus/projects?type=classic but I envision a much larger CT, obviously.)

Also I accepted the PR to add the completed generated template into the bottom of the files, so it conflicts with this. I think it should be probably easy to merge the two (though also sorry about causing a merge conflict here!).

2023-02-28 01:12 UTC, geekygirlsarah approved these changes
Alright, it's incredibly delayed, but I think this is good after your latest changes. I'll merge it in.

Thanks for the big refactor/merge!

2023-02-28 01:12 UTC, merged