Add Rust Lists
codethesaurus/codethesaur.us pull request #610
Opened 2022-10-19 16:27 UTC by michaeljones32

## What GitHub issue does this PR apply to?

 

Resolves #292

## What changed and why?

I have filled out lists.json for the Rust language
   

## Checklist
   
- [x] I claimed any associated issue(s) and they are not someone else's
- [x] I have looked at documentation to ensure I made any revisions correctly
- [x] I tested my changes locally to ensure they work
- [ ] [N/A] (If editing Django) I have added or edited any appropriate unit tests for my changes

## Any additional comments or things to be aware of while reviewing?

2022-10-21 01:28 UTC, cafce25 requested changes

2022-10-21 01:28 UTC, cafce25 commented on web/thesauruses/rust/1/lists.json
> +    },
Sorted here means it keeps the elements in some form of order I think a `BTreeSet` would fit here.

2022-10-21 01:28 UTC, cafce25 commented on web/thesauruses/rust/1/lists.json
> +    },
Maybe use something like `vec[x..y].iter().map(Clone::clone).collect::<Vec<_>>()`?
Or a variation using `clone_from_slice`/`copy_from_slice`...
Although neither is not the prettiest code I've ever seen

2022-10-21 01:28 UTC, cafce25 commented on web/thesauruses/rust/1/lists.json
> +      "code": "vec.iter().max();"
I think we should either `unwrap` like in L222 or note that they return `Option<T>`?

2022-10-21 01:28 UTC, cafce25 commented on web/thesauruses/rust/1/lists.json
> +    "name_of_sorted_mutable_list": {
what happened to these?
```
"name_of_ordered_mutable_list",
"create_a_ordered_mutable_list",
"ordered_mutable_list_start_number",
"ordered_mutable_list_can_be_appended",
"ordered_mutable_list_can_be_inserted_in_middle",
"access_element_in_ordered_mutable_list",
"insert_into_beginning_of_ordered_mutable_list",
"insert_into_end_of_ordered_mutable_list",
"insert_into_middle_of_ordered_mutable_list",
"erase_element_at_beginning_of_ordered_mutable_list",
"erase_element_at_end_of_ordered_mutable_list",
"erase_element_in_middle_of_ordered_mutable_list",
"swap_elements_in_ordered_mutable_list",
"delete_ordered_mutable_list"
```

I believe this is where `Vec` should be.

2022-10-21 01:28 UTC, cafce25 commented on web/thesauruses/rust/1/lists.json
> +      "code": "vec.iter().filter(|&item| {expression}).collect();"
You should change `&item` to `item` in both since that will only work for `Copy` types
and we shouldn't assume that here.

2022-10-21 01:28 UTC, cafce25 commented on web/thesauruses/rust/1/lists.json
> +      "code": "vec.resize(new_len, T);"
Capitalized identifiers like `T` usually denote a type in rust, I'd rather use somethig like `item`.

2022-10-21 01:28 UTC, cafce25 commented on web/thesauruses/rust/1/lists.json
> +      "code": "vec.iter().position(|&r| r == \"foo\").unwrap();"
Like below `&r` only works for types that implement `Copy`.

2022-10-22 15:47 UTC, geekygirlsarah commented on web/thesauruses/rust/1/lists.json
> +    },
I mean, perhaps, but it might also be debated if a B-tree is a "list" or not. (I do have "trees" as a future structure/concept.)

2022-10-22 15:50 UTC, geekygirlsarah requested changes
@cafce25 has some good points, so I'm going to request changes. If some of them aren't right, feel free to let us know why. (I'm familiar with Rust but haven't really made anything with it, so I can't comment too much.)

But you should include all the ID fields because the system needs those, even if the concept doesn't exist in the language.

2022-10-22 15:50 UTC, geekygirlsarah commented on web/thesauruses/rust/1/lists.json
> +    "name_of_sorted_mutable_list": {
Oh yeah, don't delete any of the IDs! They show up as "Unknown" on the page. (I imagine you'd see that if you ran it locally.) If they don't exist, add a "not-implemented" to them. If `Vec` is a fit (as cafce suggests), then you should implement them.

2022-11-12 03:47 UTC, geekygirlsarah commented
@michaeljones32 Just checking in on this again... are you able to make the changes? Do you have any questions?

2022-11-26 15:01 UTC, geekygirlsarah commented
Since it's been over a month since changes were asked for and we haven't heard from you, I'm going to go ahead and close this PR and unassign you from the issue. If you want to continue work on it, let me know and I can re-open the PR and reassign you to the issue if it's available.

2022-11-26 15:01 UTC, closed without merging