Add data_types.json entry for Clojure
codethesaurus/codethesaur.us pull request #615
Opened 2022-10-21 02:37 UTC by jeff303

## What GitHub issue does this PR apply to?

No issue opened, just working to add more complete Clojure support.

## What changed and why?

Adding data types support for Clojure

## Checklist

   

- [N/A] I claimed any associated issue(s) and they are not someone else's
- [X] I have looked at documentation to ensure I made any revisions correctly
- [X] I tested my changes locally to ensure they work
- [N/A] (If editing Django) I have added or edited any appropriate unit tests for my changes

## Any additional comments or things to be aware of while reviewing?

2022-10-22 16:10 UTC, geekygirlsarah requested changes
I see some missing ID fields like `signed_integer_8_bit` and `unsigned_integer_8_bit` for instance. If they're not there, don't delete them but add "not-implemented" to them as the site shows "Unknown" for them if they're missing. 

(Did you _actually_ test your changes? You checked the box on the PR template.)

![image](https://user-images.githubusercontent.com/2601974/197349497-5d94f2de-f521-41bc-9e04-7a5a544a587b.png)

2022-10-24 19:29 UTC, jeff303 commented
> I see some missing ID fields like `signed_integer_8_bit` and `unsigned_integer_8_bit` for instance. If they're not there, don't delete them but add "not-implemented" to them as the site shows "Unknown" for them if they're missing.

Fixed.

> (Did you _actually_ test your changes? You checked the box on the PR template.)

Yes, but clearly not thoroughly enough.  I basically started from one of the Java entries (which is also missing a few of these entirely), since the type system is essentially identical, so I thought it would be the shortest path.  I confirmed there are no more `Unknown` rows on the data types page as of the latest commit.

2022-10-27 03:52 UTC, geekygirlsarah commented
> Yes, but clearly not thoroughly enough. I basically started from one of the Java entries (which is also missing a few of these entirely), since the type system is essentially identical, so I thought it would be the shortest path. I confirmed there are no more `Unknown` rows on the data types page as of the latest commit.

Ahh, that makes sense. Another PR is trying to work on a nicer way of filling in the empty IDs in a bit of an easier way since not all of the language files are all completely filled out due to meta file changes over time.

2022-10-27 03:53 UTC, geekygirlsarah approved these changes

2022-10-27 04:02 UTC, merged