Add logical and bitwise operators for Java
codethesaurus/codethesaur.us pull request #621
Opened 2022-10-21 03:18 UTC by jeff303

## What GitHub issue does this PR apply to?

Resolves #620

## What changed and why?

Added logical operators that are supported in Java.  The "and assignment" variants are not implemented in Java (see [here](https://stackoverflow.com/q/2324549)).

## Checklist

- [X] I claimed any associated issue(s) and they are not someone else's
- [X] I have looked at documentation to ensure I made any revisions correctly
- [X] I tested my changes locally to ensure they work
- [ ] (If editing Django) I have added or edited any appropriate unit tests for my changes

2022-10-21 15:05 UTC, gutogalego approved these changes
This looks good. There are still a couple of missing bitwise operators, [reference here](https://www.geeksforgeeks.org/bitwise-operators-in-java/), although I don't know when they were introduced.

2022-10-22 16:18 UTC, geekygirlsarah requested changes
Like @gutogalego said, there's some missing operators. (I know you made the issue originally for just logic operators but it really makes sense to make the PR update all the operators, not just some of them.)

Also it'd be helpful to show where the operands go relative to operators. (Most languages do like `a + b` but some like Lisp do `(+ a b)` so I'm trying to get those updated.)

If you can add those in, I can merge this in.

![image](https://user-images.githubusercontent.com/2601974/197349906-d8f882c2-97bb-428e-8088-153435588790.png)

2022-10-24 20:45 UTC, jeff303 commented
> Like @gutogalego said, there's some missing operators. (I know you made the issue originally for just logic operators but it really makes sense to make the PR update all the operators, not just some of them.)
> 
> Also it'd be helpful to show where the operands go relative to operators. (Most languages do like `a + b` but some like Lisp do `(+ a b)` so I'm trying to get those updated.)
> 
> If you can add those in, I can merge this in.

I updated the Java 11 language file with all of these suggestions.  Once this looks good, I can apply the same changes to the other Java versions (since all of this will be identical across all three).

2022-10-27 04:18 UTC, geekygirlsarah requested changes
Make similar changes to v15 and v17 and this should be good to merge!

2022-10-27 04:18 UTC, geekygirlsarah commented on web/thesauruses/java/15/operators.json
> +    "logical_and": {
You added operand placement in Java 11's file but not 15 and 17. Could you do the same for those as well?

2022-11-04 16:26 UTC, geekygirlsarah requested changes
Two tiny swaps and I'll merge it!

2022-11-04 16:26 UTC, geekygirlsarah commented on web/thesauruses/java/11/operators.json
> +      "code": "x++\n++x",
Your examples are post-increment then pre-increment, but mention it's pre then post. Can you swap one of those so they match?

2022-11-04 16:26 UTC, geekygirlsarah commented on web/thesauruses/java/11/operators.json
> +      "code": "x--\n--x",
Same here.

2022-11-06 20:14 UTC, jeff303 commented
> Two tiny swaps and I'll merge it!

Finally got these all fixed up (I believe).  Tested the comparison page between 11-15 and 11-17.

2022-11-08 18:40 UTC, geekygirlsarah approved these changes
Great! I'll merge this in. Thanks for the changes!

2022-11-08 18:40 UTC, merged