Added Draft mode
codethesaurus/codethesaur.us pull request #636
Opened 2022-10-23 13:36 UTC by ulyssear

## What GitHub issue does this PR apply to?

Resolves #635 

## What changed and why?

   * New command `generate_missing_template` which generates all missing thesaurus.
     ```bash
     python manage.py generate_missing_template 
     ```

   * New argument `--draft` for command `generate_template` which defines draft mode for the generated thesaurus.
     ```bash
     python manage.py generate_templates --language_version=<language_version> --draft <language> <structure> 
     ```

   * New parameter `draft` for `generate_language_template`
     ```python
     generate_language_template(language_id, structure_id, version=None, draft=False)
     ```

   * New function in the Language model  named `is_draft`
     ```python
     def is_draft(self, version, structure_key):
         """
         Returns a Boolean if the version is a draft

         :param version: the version of the language
         :param structure_key: the ID for the structure to load
         :return: Boolean if the version is a draft
         """
         file_name = f"{structure_key}.json"
         file_path = os.path.join(self.language_dir, version, file_name)
         with open(file_path, 'r', encoding='UTF-8') as file:
             file_json = json.load(file)
             return file_json["meta"].get("draft", False)
     ```

## (If editing Django app) Please add screenshots

  ![image](https://user-images.githubusercontent.com/11415595/197394566-e10b4290-176b-4ebb-b985-a8390d760cba.png)
  _Warning on reference page_

  ![image](https://user-images.githubusercontent.com/11415595/197394619-e3d2e92e-8a14-45f8-8e3e-b78944593f39.png)
  _Warning on compare page_

## Checklist

- [ ] I claimed any associated issue(s) and they are not someone else's
- [x] I have looked at the documentation to ensure I made any revisions correctly
- [x] I tested my changes locally to ensure they work
- [ ] (If editing Django) I have added or edited any appropriate unit tests for my changes

## Any additional comments or things to be aware of while reviewing?

  The PR is not ready yet.

2022-10-23 15:30 UTC, ulyssear commented
I'm working on unit tests, but I have no idea how I could add draft mode. 
Would it be possible to have a track of what I could put?

2022-11-14 03:05 UTC, geekygirlsarah requested changes
So besides the two comments, when I go to the [review app](https://codethesaurus-test-pr-636.herokuapp.com/reference/?concept=functions&lang=ada%3B2012), I don't see the UI addition. Shouldn't I see it here?

![image](https://user-images.githubusercontent.com/2601974/201566453-de2142f5-0952-450b-ae98-c715cc5958c7.png)

2022-11-14 03:05 UTC, geekygirlsarah commented on web/thesaurus_template_generators.py
> +def generate_language_template(language_id, structure_id, version=None, draft=False):
Should this get removed as I think we decided against "draft mode"?

2022-11-14 03:05 UTC, geekygirlsarah commented on web/thesaurus_template_generators.py
> +        meta['draft'] = True
Same for removing this

2022-11-14 11:56 UTC, ulyssear commented on web/thesaurus_template_generators.py
> +def generate_language_template(language_id, structure_id, version=None, draft=False):
I forgot to remove it, sorry for that.

2022-11-15 09:36 UTC, ulyssear commented
> So besides the two comments, when I go to the [review app](https://codethesaurus-test-pr-636.herokuapp.com/reference/?concept=functions&lang=ada%3B2012), I don't see the UI addition. Shouldn't I see it here?
> 
> ![image](https://user-images.githubusercontent.com/2601974/201566453-de2142f5-0952-450b-ae98-c715cc5958c7.png)

OK, I know what's happened: the method "is_incomplete" checks if the code fields are empty in the template inside the thesaurus folder. But in the case of some files, these entries (with "Unknown") don't have the field and thus, no condition is done there (so, the result will be False, instead of True).
We have to check with the complete template but I don't know if it's a good practice, I will even so put this solution.

2023-02-28 01:20 UTC, geekygirlsarah commented
I'm going to go ahead and close this because there's some merge conflicts and I haven't seen activity since November.

If you want to keep working on it, you're welcome to! You can reopen this or make a new pull request to keep working on it.

Thanks for the work you've put into it so far!

2023-02-28 01:20 UTC, closed without merging

2023-02-28 12:06 UTC, ulyssear commented
I'll check on my side to fix the merge conflicts !
I may do this this week, or next week at the latest.