adds lists for r lang
codethesaurus/codethesaur.us pull request #649
Opened 2022-10-31 23:13 UTC by monkeywithacupcake

## What GitHub issue does this PR apply to?

Resolves #577

## What changed and why?

 added lists.json for R because it was not there

## Checklist

   

- [X] I claimed any associated issue(s) and they are not someone else's
- [X] I have looked at documentation to ensure I made any revisions correctly
- [X] I tested my changes locally to ensure they work
- [ ] (If editing Django) I have added or edited any appropriate unit tests for my changes

## Any additional comments or things to be aware of while reviewing?

In some places, I really wanted to add caveats that you probably would not use a "list" in r for this. So, I expect we will have future edits.

2022-11-04 17:55 UTC, geekygirlsarah requested changes
Two tiny clarifications and I think this is good to merge!

2022-11-04 17:55 UTC, geekygirlsarah commented on web/thesauruses/r/4/lists.json
> +      },
I think this is intended to be a yes/no kind of question (as how you append is below)

2022-11-04 17:55 UTC, geekygirlsarah commented on web/thesauruses/r/4/lists.json
> +            "mylist <- append(mylist, list(x = 42), 2)"
Is it safe to assume the `,2` is to insert in position 2? But also does this start at 0 or at 1, or is it based on the numbering from the list on the line above? Maybe add a `comment:` to clarify?

2022-11-04 23:53 UTC, monkeywithacupcake commented
thanks for that @geekygirlsarah  - the yes/no questions kept tripping me up!

2022-11-08 18:44 UTC, geekygirlsarah approved these changes
Sweet, I'll merge this in. Thank you for adding more R to the site!

2022-11-08 18:45 UTC, merged