Akkshay tandon  adding c language
codethesaurus/codethesaur.us pull request #659
Opened 2023-01-19 17:38 UTC by akkshayTandon

## What GitHub issue does this PR apply to?

 

none

## What changed and why?

 added strings for C language

## Checklist

   

- [ ] I claimed any associated issue(s) and they are not someone else's
- [ ] I have looked at documentation to ensure I made any revisions correctly
- [ ] I tested my changes locally to ensure they work
- [ ] (If editing Django) I have added or edited any appropriate unit tests for my changes

## Any additional comments or things to be aware of while reviewing?

2023-02-28 16:55 UTC, akkshayTandon reviewed
Do I need to do something?

2023-02-28 18:00 UTC, geekygirlsarah commented
I pulled this PR up yesterday and was getting an error on the project and I couldn't tell if it was from your file or from another PR I merged in, and I wanted to figure that out first. So I need to find that bug first.

2023-03-09 16:55 UTC, akkshayTandon commented
Hey @geekygirlsarah can you add a label for C language also?

2023-10-02 15:11 UTC, geekygirlsarah requested changes

2023-10-02 15:11 UTC, geekygirlsarah commented on web/thesauruses/c/17/strings.json
> +      ],
If it's not implemented, you shouldn't include an algorithm to do it since this is a language reference tool.

2023-10-02 15:11 UTC, geekygirlsarah commented on web/thesauruses/c/17/strings.json
> +      ],
Same here.

2023-10-02 15:11 UTC, geekygirlsarah commented on web/thesauruses/c/17/strings.json
> +      ],
Same here.

2023-10-02 15:11 UTC, geekygirlsarah commented on web/thesauruses/c/17/strings.json
> +      ],
Same here.

2023-10-02 15:11 UTC, geekygirlsarah commented on web/thesauruses/c/17/strings.json
> +      ],
Same here.

2023-10-02 15:11 UTC, geekygirlsarah commented on web/thesauruses/c/17/strings.json
> +      ],
This is implemented, it's `toupper(str[i])`. Just make the `#include` and the `toupper` the code part.

2023-10-02 15:11 UTC, geekygirlsarah commented on web/thesauruses/c/17/strings.json
> +      ],
Same for `tolower()` here.  (also you have `toupper` here.)

2023-10-02 15:11 UTC, geekygirlsarah commented on web/thesauruses/c/17/strings.json
> +    }
Several of these are implemented. See https://www.geeksforgeeks.org/format-specifiers-in-c/ .

2023-10-29 17:14 UTC, geekygirlsarah commented
Checking in again to see how this is coming along

2023-11-28 00:07 UTC, geekygirlsarah commented
Since I haven't heard from you in a while, I'm going to close this PR so someone else can work on the issue.

If you want to take it back on, you're welcome to reopen this PR and pick up where you left off.

2023-11-28 00:07 UTC, closed without merging

2023-11-30 17:25 UTC, akkshayTandon commented
He, apologies for not being active. But I have tried to make these changes. I will open a new PR for this one.
My exams are about to start, so might not be able to update the changes actively.

2023-11-30 18:26 UTC, geekygirlsarah commented
That's fine! I'll leave you on the issue and can see if I can reopen this. (If not, making a new PR is fine.)

2023-11-30 18:26 UTC, geekygirlsarah commented
Reopening...

2023-12-06 19:49 UTC, akkshayTandon commented
I have opened a new PR #714