Fixes issue#546
codethesaurus/codethesaur.us pull request #664
Opened 2023-03-01 10:43 UTC by Neeraj8949

## What GitHub issue does this PR apply to?

 

Resolves #546 

## What changed and why?

   

## (If editing Django app) Please add screenshots

   

## Checklist

   

- [ ] I claimed any associated issue(s) and they are not someone else's
- [ ] I have looked at documentation to ensure I made any revisions correctly
- [ ] I tested my changes locally to ensure they work
- [ ] (If editing Django) I have added or edited any appropriate unit tests for my changes

## Any additional comments or things to be aware of while reviewing?

2023-03-01 11:22 UTC, cafce25 commented
For reference it would really help if you add the info that you added queues and stacks to C++ under the "What changed and why?" section in my opinion. As it is currently one has to search for that info elsewhere.

2023-10-02 15:20 UTC, geekygirlsarah commented
![image](https://github.com/codethesaurus/codethesaur.us/assets/2601974/2217d5fb-9f71-4541-badf-7d57cc4f5233)

Did you follow the directions when making this? The concept names have to match up with what's expected and they don't. Follow the directions here to do it correctly:  https://docs.codethesaur.us/thesaurus/add-lang-concept/ 

You're welcome to try this again by pushing to your branch/repo again.

2023-10-02 15:21 UTC, geekygirlsarah requested changes

2023-10-02 15:21 UTC, geekygirlsarah commented on web/thesauruses/cpp/C++17/queues_stacks.json
> +        "structure": "queue and stacks"
This should be the name of the JSON file (so `queues_stacks`)

2023-10-02 15:21 UTC, geekygirlsarah commented on web/thesauruses/cpp/C++17/queues_stacks.json
> +      }
These are not valid concept names. (See previous comment.)

2023-10-29 15:59 UTC, geekygirlsarah commented
I'm closing this PR has the changes haven't been made and I haven't heard from you. You are welcome to reclaim the issue and work on it some more if you want. If you do want it, please read https://docs.codethesaur.us to see how to properly create and add the file.

2023-10-29 15:59 UTC, closed without merging