Adding warnings about thesaurus incomplete
codethesaurus/codethesaur.us pull request #665
Opened 2023-03-07 16:25 UTC by ulyssear

New PR for #636 
Will close #635

2023-10-02 18:49 UTC, geekygirlsarah commented
Belated, but I think I like this. I think I have two main thoughts:

1. Can it just show one yellow box at the top rather than repeatedly throughout the page? It's not that pressing of an issue, and it's showing up in categories that are complete.
2. Can you take off "Warning!" as it's not like the values are wrong or anything, they're just missing.

2023-10-16 22:07 UTC, geekygirlsarah requested changes
See previous comment.

2023-10-18 11:03 UTC, ulyssear commented
Hi ! Sorry for the time to answer, i'm busy this month.
To answer at your first question, i like your idea : it will be better to have a single "alert" at top of page instead at top of section indeed.
For your last question, of course i can edit that.
I don't know if i can do this the nearly days but i will be more available to do this the next week.

2023-10-28 11:28 UTC, ulyssear commented
Hello!

I have made the modifications. Can you please check if all is good for the pull request?

There is a list of what it's done with the current pull request :
  - Each language for each category is checked (if there is a better solution to do that, I am interested): if there is at least one entry unknown, it's incomplete.
  - Alert for a category and a language (it's not a warning). The content is: "The category seems to be incomplete. Help us improve !" where "Help us improve!" is a link to the category (for the language).


Furthermore, i had a problem with docker when launching the project. A line has added in Dockerfile that fixed the problem. Can you please check that to see if it can be add to the stable branch ?

The problem was "Error: pg_config executable not found" fixed by adding the package via aptitude.

2023-10-28 15:32 UTC, ulyssear commented
I removed the alerts inside the header of each category to have alerts at the top of page instead.

Screenshot of what it should render for a language's incomplete thesaurus below.

![image](https://github.com/codethesaurus/codethesaur.us/assets/11415595/f9bc30b4-5689-4c98-b030-6f6085cb64dd)

2023-10-29 16:27 UTC, geekygirlsarah commented on web/templates/compare.html
Why is this file being added? Was this a file for testing?

2023-11-01 01:53 UTC, geekygirlsarah commented
GitHub keeps telling me you made changes, but you keep force-pushing and so I can't compare and see what is new since the last review. Can you summarize the last 2 days of work since my last comment?

2023-11-05 15:03 UTC, ulyssear commented
I created a new pull request, it will better for the merge. This pull request can be closed.

2023-11-08 11:05 UTC, closed without merging